services:
  db:
    ports: []
    environment:
      - POSTGRES_DB=isp_production_db
      - POSTGRES_USER=isp_db_admin
      - POSTGRES_PASSWORD=PgSql_2025_Sec_9vT8xK2mQ7nB3fH
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U isp_db_admin"]
      timeout: 10s
      interval: 30s
      retries: 3

  redis:
    ports: []
    command: redis-server --requirepass Redis2025SecureAuth --appendonly yes --appendfsync everysec

  web:
    environment:
      - DATABASE_URL=postgresql://isp_db_admin:PgSql_2025_Sec_9vT8xK2mQ7nB3fH@db:5432/isp_production_db
      - REDIS_URL=redis://:Redis2025SecureAuth@redis:6379/0
    ports:
      - "8000:8000"

  rq_worker:
    environment:
      - DATABASE_URL=postgresql://isp_db_admin:PgSql_2025_Sec_9vT8xK2mQ7nB3fH@db:5432/isp_production_db
      - REDIS_URL=redis://:Redis2025SecureAuth@redis:6379/0

  prometheus:
    ports: []

  grafana:
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin_isp
      - GF_SECURITY_ADMIN_PASSWORD=Grafana2025AdminSecure

  node-exporter:
    ports: []

  redis-exporter:
    ports: []
    environment:
      - REDIS_ADDR=redis://redis:6379
      - REDIS_PASSWORD=Redis2025SecureAuth

  postgres-exporter:
    ports: []
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable