version: "3.3"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_PORT=6380
      - DJANGO_SETTINGS_MODULE=olt_connector.settings

  redis:
    image: redis:7.2
    ports:
      - "6380:6379"

  rq_worker:
    build: .
    command: python /code/manage.py rqworker default
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_PORT=6380
      - DJANGO_SETTINGS_MODULE=olt_connector.settings

volumes:
  postgres_data: