# CONFIGURAÇÃO DE SEGURANÇA CORRIGIDA - SEM SENHAS EXPOSTAS
# Use: docker compose -f docker-compose.yml -f docker-compose.security-safe.yml up

services:
  db:
    ports: []
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      timeout: 10s
      interval: 30s
      retries: 3

  redis:
    ports: []
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --appendfsync everysec

  web:
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    ports:
      - "8000:8000"

  rq_worker:
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0

  prometheus:
    ports: []

  grafana:
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin_isp}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

  node-exporter:
    ports: []

  redis-exporter:
    ports: []
    environment:
      - REDIS_ADDR=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  postgres-exporter:
    ports: []
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@db:5432/postgres?sslmode=disable

networks:
  app-network:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.20.0.0/16