version: "3.3"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=isp.settings

  redis:
    image: redis:7.2
    command: redis-server --save "" --appendonly no
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  rq_worker:
    build: .
    command: python /code/manage.py rqworker default
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=isp.settings

volumes:
  postgres_data:
  redis_data: