global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@isp-monitoring.local'
  smtp_auth_username: 'alertmanager@isp-monitoring.local'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@empresa.com'
        subject: '[CRÍTICO] {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          {{ range .Alerts }}
          Alerta: {{ .Annotations.summary }}
          Descrição: {{ .Annotations.description }}
          Severidade: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          Tempo: {{ .StartsAt }}
          {{ end }}
        html: |
          <h2>Alerta Crítico - Sistema ISP</h2>
          {{ range .Alerts }}
          <p><strong>Alerta:</strong> {{ .Annotations.summary }}</p>
          <p><strong>Descrição:</strong> {{ .Annotations.description }}</p>
          <p><strong>Severidade:</strong> <span style="color: red;">{{ .Labels.severity }}</span></p>
          <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
          <p><strong>Tempo:</strong> {{ .StartsAt }}</p>
          <hr>
          {{ end }}
    webhook_configs:
      - url: 'http://web:8000/api/alerts/webhook'
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'admin@empresa.com'
        subject: '[AVISO] {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          {{ range .Alerts }}
          Alerta: {{ .Annotations.summary }}
          Descrição: {{ .Annotations.description }}
          Severidade: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          Tempo: {{ .StartsAt }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']