# Generated by Django 4.0.8 on 2023-01-25 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='olt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Slot')),
                ('port', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Porta')),
                ('users_connected', models.IntegerField(verbose_name='Usuários Aprovisionados')),
            ],
            options={
                'verbose_name': 'Olt',
                'verbose_name_plural': "Olt's",
            },
        ),
    ]
