# Generated by Django 4.0.8 on 2023-02-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0003_onu_alter_oltusers_port_alter_oltusers_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaOnu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassi', models.CharField(max_length=20, verbose_name='Chassi')),
                ('position', models.IntegerField(verbose_name='Posição do Slot')),
            ],
            options={
                'verbose_name': 'ONU',
                'verbose_name_plural': 'ONUs',
            },
        ),
    ]
