# Generated by Django 4.0.8 on 2023-02-03 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0005_alter_oltusers_options_alter_placaonu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placaonu',
            name='position',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Posição do Slot'),
        ),
    ]
