# Generated by Django 4.0.8 on 2023-06-28 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0006_alter_placaonu_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='oltusers',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 12, 37, 26, 256334, tzinfo=utc), verbose_name='Última Atualização'),
            preserve_default=False,
        ),
    ]
