# Generated by Django 4.0.8 on 2024-02-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0007_oltusers_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='onu',
            name='admin_state',
            field=models.CharField(blank=True, default='up', max_length=30, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='onu',
            name='signal_rx',
            field=models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Signal RX'),
        ),
    ]
