# Generated by Django 4.0.8 on 2024-06-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0010_clientefibraixc'),
    ]

    operations = [
        migrations.AddField(
            model_name='onu',
            name='cliente_fibra',
            field=models.BooleanField(default=False, verbose_name='Cliente Fibra'),
        ),
    ]
