# Generated by Django 4.0.8 on 2025-04-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0011_onu_cliente_fibra'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientefibraixc',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientefibraixc',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientefibraixc',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
