# Generated by Django 4.0.8 on 2025-04-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0012_clientefibraixc_endereco_clientefibraixc_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientefibraixc',
            name='id_caixa_ftth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
