# Generated by Django 4.0.8 on 2025-04-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0013_clientefibraixc_id_caixa_ftth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onu',
            name='olt_rx_sig',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='OLT RX Signal'),
        ),
    ]
