# Generated by Django 4.2.25 on 2025-11-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0014_alter_onu_olt_rx_sig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(help_text='IP individual (ex: 192.168.1.1) ou range CIDR (ex: 192.168.1.0/24)', max_length=50, unique=True, verbose_name='IP/Range')),
                ('description', models.CharField(help_text='Descrição do IP ou range (ex: Servidor, Rede local, etc.)', max_length=200, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Se marcado, este IP será permitido no sistema', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'IP Permitido',
                'verbose_name_plural': 'IPs Permitidos',
                'ordering': ['ip_address'],
            },
        ),
        migrations.CreateModel(
            name='OltSfpDiagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=50, unique=True, verbose_name='Interface')),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante')),
                ('part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número da Peça')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serial')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperatura (°C)')),
                ('voltage', models.FloatField(blank=True, null=True, verbose_name='Voltagem (V)')),
                ('tx_power', models.FloatField(blank=True, null=True, verbose_name='Potência TX (dBm)')),
                ('rx_power', models.FloatField(blank=True, null=True, verbose_name='Potência RX (dBm)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Diagnóstico SFP',
                'verbose_name_plural': 'Diagnósticos SFP',
                'ordering': ['interface'],
            },
        ),
        migrations.CreateModel(
            name='OltSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=20, unique=True, verbose_name='Nome do Slot')),
                ('actual_type', models.CharField(max_length=50, verbose_name='Tipo Atual')),
                ('enabled', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('error_status', models.CharField(max_length=100, verbose_name='Status de Erro')),
                ('availability', models.CharField(max_length=50, verbose_name='Disponibilidade')),
                ('restart_count', models.IntegerField(default=0, verbose_name='Contador de Reinicializações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Slot OLT',
                'verbose_name_plural': 'Slots OLT',
                'ordering': ['slot_name'],
            },
        ),
        migrations.CreateModel(
            name='OltSystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isam_release', models.CharField(max_length=50, verbose_name='ISAM Release')),
                ('uptime_days', models.IntegerField(default=0, verbose_name='Uptime (dias)')),
                ('uptime_hours', models.IntegerField(default=0, verbose_name='Uptime (horas)')),
                ('uptime_minutes', models.IntegerField(default=0, verbose_name='Uptime (minutos)')),
                ('uptime_seconds', models.IntegerField(default=0, verbose_name='Uptime (segundos)')),
                ('uptime_raw', models.CharField(max_length=255, verbose_name='Uptime Raw')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Informação do Sistema OLT',
                'verbose_name_plural': 'Informações do Sistema OLT',
            },
        ),
        migrations.AddField(
            model_name='clientefibraixc',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.CreateModel(
            name='OltTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=20, verbose_name='Nome do Slot')),
                ('sensor_id', models.IntegerField(verbose_name='ID do Sensor')),
                ('actual_temp', models.IntegerField(verbose_name='Temperatura Atual (°C)')),
                ('tca_low', models.IntegerField(verbose_name='TCA Baixo (°C)')),
                ('tca_high', models.IntegerField(verbose_name='TCA Alto (°C)')),
                ('shutdown_low', models.IntegerField(verbose_name='Shutdown Baixo (°C)')),
                ('shutdown_high', models.IntegerField(verbose_name='Shutdown Alto (°C)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Temperatura OLT',
                'verbose_name_plural': 'Temperaturas OLT',
                'ordering': ['slot_name', 'sensor_id'],
                'unique_together': {('slot_name', 'sensor_id')},
            },
        ),
    ]
