# Generated by Django 4.2.30 on 2026-08-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0015_allowedip_oltsfpdiagnostics_oltslot_oltsysteminfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientefibraixc',
            name='id_contrato',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ID do contrato (IXC)'),
        ),
        migrations.AddField(
            model_name='clientefibraixc',
            name='vinculado',
            field=models.BooleanField(default=False, help_text='True quando id_contrato existe e foi encontrado em cliente_contrato/cliente no IXC (nome/endereço são dados reais do cadastro). False = registro de provisionamento (radpop_radio_cliente_fibra) sem contrato formal vinculado no IXC.', verbose_name='Vinculado a contrato'),
        ),
    ]
