# Generated by Django 4.2.25 on 2025-11-10 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0015_allowedip_oltsfpdiagnostics_oltslot_oltsysteminfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OltSystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='CPU (%)')),
                ('cpu_load', models.FloatField(blank=True, null=True, verbose_name='CPU Load Average')),
                ('mem_percent', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Memória (%)')),
                ('model', models.CharField(default='FX-4', max_length=50, verbose_name='Modelo')),
                ('uptime_days', models.IntegerField(default=0, verbose_name='Uptime (dias)')),
                ('total_slots', models.IntegerField(default=0, verbose_name='Total de Slots')),
                ('operational_slots', models.IntegerField(default=0, verbose_name='Slots Operacionais')),
                ('avg_temperature', models.FloatField(blank=True, null=True, verbose_name='Temperatura Média (°C)')),
                ('max_temperature', models.FloatField(blank=True, null=True, verbose_name='Temperatura Máxima (°C)')),
                ('critical_temps', models.IntegerField(default=0, verbose_name='Temperaturas Críticas')),
                ('warning_temps', models.IntegerField(default=0, verbose_name='Temperaturas de Aviso')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='Medido em')),
            ],
            options={
                'verbose_name': 'Estatística da OLT',
                'verbose_name_plural': 'Estatísticas da OLT',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['measured_at'], name='olt_oltsyst_measure_027c19_idx'), models.Index(fields=['-measured_at'], name='olt_oltsyst_measure_4cc4b9_idx')],
            },
        ),
    ]
