# Generated by Django 4.2.24 on 2025-09-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0016_oltsfpdiagnostics_oltslot_oltsysteminfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oltsysteminfo',
            name='uptime_raw',
            field=models.CharField(max_length=255, verbose_name='Uptime Raw'),
        ),
    ]
