# Generated by Django 4.2.25 on 2025-11-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0016_add_olt_system_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='OltAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(choices=[('current', 'Alarme Atual'), ('major', 'Alarme Major'), ('critical', 'Alarme Crítico'), ('log', 'Log de Alarmes')], max_length=20, verbose_name='Tipo de Alarme')),
                ('severity', models.CharField(blank=True, choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical'), ('warning', 'Warning'), ('clear', 'Clear')], max_length=20, null=True, verbose_name='Severidade')),
                ('alarm_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Alarme')),
                ('entity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidade')),
                ('description', models.TextField(verbose_name='Descrição do Alarme')),
                ('alarm_time', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Alarme')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='Coletado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Alarme OLT',
                'verbose_name_plural': 'Alarmes OLT',
                'ordering': ['-alarm_time', '-collected_at'],
            },
        ),
    ]
