# Generated by Django 4.2.30 on 2026-08-31 19:54

from django.db import migrations, models
import django.db.models.deletion
import olt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0016_clientefibraixc_id_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('vendor', models.CharField(choices=[('nokia_alcatel', 'Nokia / Alcatel (AOS)')], default='nokia_alcatel', max_length=30, verbose_name='Fabricante')),
                ('device_type', models.CharField(default='alcatel_aos', max_length=50, verbose_name='Device type (netmiko)')),
                ('host', models.CharField(max_length=255, verbose_name='Host/IP')),
                ('username', models.CharField(max_length=100, verbose_name='Usuário SSH')),
                ('password', olt.fields.EncryptedCharField(max_length=500, verbose_name='Senha SSH')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='Porta SSH')),
                ('global_delay_factor', models.IntegerField(default=2, verbose_name='Global delay factor (netmiko)')),
                ('verbose', models.BooleanField(default=False, verbose_name='Verbose (netmiko)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'OLT',
                'verbose_name_plural': 'OLTs',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='oltsfpdiagnostics',
            name='interface',
            field=models.CharField(max_length=50, verbose_name='Interface'),
        ),
        migrations.AlterField(
            model_name='oltslot',
            name='slot_name',
            field=models.CharField(max_length=20, verbose_name='Nome do Slot'),
        ),
        migrations.AlterUniqueTogether(
            name='olttemperature',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='oltsfpdiagnostics',
            name='olt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sfp_diagnostics', to='olt.olt', verbose_name='OLT'),
        ),
        migrations.AddField(
            model_name='oltslot',
            name='olt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='olt.olt', verbose_name='OLT'),
        ),
        migrations.AddField(
            model_name='oltsysteminfo',
            name='olt',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_info', to='olt.olt', verbose_name='OLT'),
        ),
        migrations.AddField(
            model_name='olttemperature',
            name='olt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='olt.olt', verbose_name='OLT'),
        ),
        migrations.AddField(
            model_name='oltusers',
            name='olt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olt_users', to='olt.olt', verbose_name='OLT'),
        ),
        migrations.AddField(
            model_name='onu',
            name='olt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onus', to='olt.olt', verbose_name='OLT'),
        ),
        migrations.AlterUniqueTogether(
            name='oltsfpdiagnostics',
            unique_together={('olt', 'interface')},
        ),
        migrations.AlterUniqueTogether(
            name='oltslot',
            unique_together={('olt', 'slot_name')},
        ),
        migrations.AlterUniqueTogether(
            name='olttemperature',
            unique_together={('olt', 'slot_name', 'sensor_id')},
        ),
    ]
