# Generated by Django 4.2.25 on 2025-11-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0017_oltalarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoIxc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ixc', models.IntegerField(unique=True, verbose_name='ID IXC')),
                ('protocolo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Protocolo')),
                ('tipo', models.CharField(choices=[('I', 'Instalação'), ('M', 'Manutenção'), ('C', 'Corretiva'), ('R', 'Retirada'), ('V', 'Visita'), ('O', 'Outros')], default='M', max_length=1, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('A', 'Aberta'), ('X', 'Executada'), ('F', 'Fechada'), ('C', 'Cancelada'), ('P', 'Pausada'), ('R', 'Reagendada')], default='A', max_length=1, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('B', 'Baixa'), ('N', 'Normal'), ('A', 'Alta'), ('U', 'Urgente')], default='N', max_length=1, verbose_name='Prioridade')),
                ('id_cliente', models.IntegerField(blank=True, null=True, verbose_name='ID Cliente')),
                ('id_contrato', models.IntegerField(blank=True, null=True, verbose_name='ID Contrato')),
                ('id_assunto', models.IntegerField(blank=True, null=True, verbose_name='ID Assunto')),
                ('assunto_nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Assunto')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('mensagem_resposta', models.TextField(blank=True, null=True, verbose_name='Mensagem Resposta')),
                ('id_tecnico', models.IntegerField(blank=True, null=True, verbose_name='ID Técnico')),
                ('tecnico_nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Técnico')),
                ('endereco', models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('referencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Referência')),
                ('data_abertura', models.DateTimeField(blank=True, null=True, verbose_name='Data Abertura')),
                ('data_agenda', models.DateTimeField(blank=True, null=True, verbose_name='Data Agendamento')),
                ('data_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Data Execução')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data Fechamento')),
                ('data_prazo_limite', models.DateTimeField(blank=True, null=True, verbose_name='Prazo Limite')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('valor_comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Comissão')),
                ('sincronizado_em', models.DateTimeField(auto_now=True, verbose_name='Sincronizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço IXC',
                'verbose_name_plural': 'Ordens de Serviço IXC',
                'ordering': ['-data_abertura', '-id_ixc'],
                'indexes': [models.Index(fields=['status'], name='olt_ordemse_status_d96e1f_idx'), models.Index(fields=['data_abertura'], name='olt_ordemse_data_ab_f7f0de_idx'), models.Index(fields=['id_assunto'], name='olt_ordemse_id_assu_cd47b0_idx'), models.Index(fields=['id_tecnico'], name='olt_ordemse_id_tecn_caa0b1_idx')],
            },
        ),
    ]
