# Generated by Django 4.2.25 on 2025-10-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0017_alter_oltsysteminfo_uptime_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(help_text='IP individual (ex: 192.168.1.1) ou range CIDR (ex: 192.168.1.0/24)', max_length=50, unique=True, verbose_name='IP/Range')),
                ('description', models.CharField(help_text='Descrição do IP ou range (ex: Servidor, Rede local, etc.)', max_length=200, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Se marcado, este IP será permitido no sistema', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'IP Permitido',
                'verbose_name_plural': 'IPs Permitidos',
                'ordering': ['ip_address'],
            },
        ),
        migrations.AddField(
            model_name='clientefibraixc',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='oltslot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='olttemperature',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
