# Generated by Django 4.2.30 on 2026-09-01 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0018_backfill_olt'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='slot_count',
            field=models.PositiveSmallIntegerField(default=2, help_text='Maior número de slot físico da OLT (mesmo que nem todos estejam instalados hoje) - define até onde olt/utils.py varre a OLT via SSH.', verbose_name='Quantidade de slots'),
        ),
        migrations.AlterField(
            model_name='oltusers',
            name='slot',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)], verbose_name='Slot'),
        ),
    ]
