# Generated by Django 4.2.25 on 2025-12-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0018_ordemservicoixc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atualizacao', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático'), ('agendado', 'Agendado')], max_length=20, verbose_name='Tipo de Atualização')),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('em_progresso', 'Em Progresso'), ('concluido', 'Concluído'), ('falhou', 'Falhou'), ('parcial', 'Parcialmente Concluído')], default='iniciado', max_length=20, verbose_name='Status')),
                ('usuario', models.CharField(default='Sistema', max_length=100, verbose_name='Usuário')),
                ('job_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('duracao_segundos', models.IntegerField(blank=True, null=True, verbose_name='Duração (segundos)')),
                ('olt_system_ok', models.BooleanField(default=False, verbose_name='Sistema OLT OK')),
                ('port_occupation_ok', models.BooleanField(default=False, verbose_name='Ocupação Portas OK')),
                ('onus_ok', models.BooleanField(default=False, verbose_name='ONUs OK')),
                ('macs_ok', models.BooleanField(default=False, verbose_name='MACs OK')),
                ('clientes_ok', models.BooleanField(default=False, verbose_name='Clientes OK')),
                ('sucessos', models.IntegerField(default=0, verbose_name='Sucessos')),
                ('total_etapas', models.IntegerField(default=5, verbose_name='Total de Etapas')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('erros', models.JSONField(blank=True, null=True, verbose_name='Erros Detalhados')),
            ],
            options={
                'verbose_name': 'Log de Atualização do Sistema',
                'verbose_name_plural': 'Logs de Atualizações do Sistema',
                'ordering': ['-iniciado_em'],
                'indexes': [models.Index(fields=['tipo_atualizacao'], name='olt_systemu_tipo_at_a697ec_idx'), models.Index(fields=['status'], name='olt_systemu_status_627f75_idx'), models.Index(fields=['iniciado_em'], name='olt_systemu_iniciad_10ea7e_idx')],
            },
        ),
    ]
