# Generated by Django 4.2.30 on 2026-10-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0019_olt_slot_count_alter_oltusers_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='onu',
            name='ont_rx_sig',
            field=models.FloatField(blank=True, null=True, verbose_name='ONT RX Signal'),
        ),
        migrations.AddField(
            model_name='onu',
            name='ont_tx_sig',
            field=models.FloatField(blank=True, null=True, verbose_name='ONT TX Signal'),
        ),
    ]
